{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sis11framework"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sis11framework"]}],"topicSections":[{"identifiers":["doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ContactActions","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/DoCmd-swift.class","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/DoCmdDto","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/LifePolicy","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Portal","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/RepoClaim","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/RepoLifePolicy","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Repository","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Sis11SDK"],"title":"Classes"},{"identifiers":["doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/City","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Claim","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Contact","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ContactData","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ContactDataOutData","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Country","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Coverage","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Credentials","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Currency","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/EventReason","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/GetPingDTO","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Insured","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/InsuredEvent","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/InsuredObject","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Issue","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueData","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueReason","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueRequest","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueResponse","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueType","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/MobilePayment","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Options","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/PayPlan","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/PortalData","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Premium","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Priority","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Product","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/QuoteConfig","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/QuotePortalProductResponse","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Relationship","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/RepoClaimDTO","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/RepoLifePolicyDTO","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ReturnedUser","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ReturnedUserOutData","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/SelfService","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/SelfServiceConfiguration","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/StateCatalog","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/StepConfig","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/doCmd-swift.struct","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/doCmdData"],"title":"Structures"},{"title":"Variables","identifiers":["doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/SDK"]},{"identifiers":["doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/APIError","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/AuthErrors","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Catalog"],"title":"Enumerations"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"This project is an iOS framework designed to enable developers to have functionalities available for rapid deployment. The framework leverages the Singleton pattern to keep user data accessible at all times.","type":"text"}]},{"type":"heading","level":2,"text":"Features","anchor":"Features"},{"items":[{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Rapid Deployment"}],"type":"strong"},{"text":": Easily integrate and deploy functionalities into your iOS app.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Singleton Pattern","type":"text"}],"type":"strong"},{"type":"text","text":": Maintains user data accessibility throughout the app’s lifecycle."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"User Data Management","type":"text"}]},{"type":"text","text":": Simplified management and retrieval of user data."}]}]}],"type":"unorderedList"},{"anchor":"Installation","type":"heading","level":2,"text":"Installation"},{"inlineContent":[{"type":"text","text":"To install the framework, follow these steps:"}],"type":"paragraph"},{"inlineContent":[{"text":"Swift Package Manager: Add the package dependency to your ","type":"text"},{"type":"codeVoice","code":"Package.swift"},{"text":" file:","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["dependencies: [","    .package(url: \"https:\/\/bitbucket.org\/axxis_systems\/sis11sdk\/\", from: \"1.0.0\")","]"],"syntax":null},{"type":"paragraph","inlineContent":[{"text":"Then add the framework as a dependency to your target:","type":"text"}]},{"type":"codeListing","syntax":null,"code":[".target(","    name: \"YourAppTarget\",","    dependencies: [\"sis11sdk\"]),"]},{"type":"paragraph","inlineContent":[{"text":"Usage","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"To use the framework, import it into your project and access its functionalities. Here’s an example:"}]},{"syntax":null,"type":"codeListing","code":["import sis11sdk","","class ViewController: UIViewController {","    override func viewDidLoad() {","        super.viewDidLoad()","","        \/\/ Access the shared instance of the singleton","        let sdk = sis11sdk.shared","","        \/\/ Use the framework's functionalities","        sdk.doAuth(credentials: Credentials(email: \"your email\", clave: \"your password\"))","    }","}"]},{"type":"heading","level":2,"text":"Singleton Pattern","anchor":"Singleton-Pattern"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The framework uses the Singleton pattern to ensure that there is only one instance of the user data manager. This instance is globally accessible and provides a centralized way to manage user data."}]}]}],"sections":[],"hierarchy":{"paths":[[]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"collection","modules":[{"name":"Sis11Framework"}],"externalID":"Sis11Framework","title":"Sis11Framework","roleHeading":"Framework","symbolKind":"module"},"references":{"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/IssueData":{"title":"IssueData","navigatorTitle":[{"text":"IssueData","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IssueData"}],"url":"\/documentation\/sis11framework\/issuedata","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueData","abstract":[],"kind":"symbol","role":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/ContactData":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ContactData","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ContactData","navigatorTitle":[{"text":"ContactData","kind":"identifier"}],"title":"ContactData","abstract":[],"url":"\/documentation\/sis11framework\/contactdata","role":"symbol","kind":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/ContactActions":{"title":"ContactActions","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ContactActions","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactActions"}],"url":"\/documentation\/sis11framework\/contactactions","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ContactActions","abstract":[{"text":"Contact Repository","type":"text"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/DoCmdDto":{"abstract":[{"text":"DoCmd  Generic full DTO","type":"text"}],"type":"topic","url":"\/documentation\/sis11framework\/docmddto","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/DoCmdDto","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DoCmdDto","kind":"identifier"}],"title":"DoCmdDto","navigatorTitle":[{"text":"DoCmdDto","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Contact":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Contact","kind":"identifier"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Contact","kind":"symbol","url":"\/documentation\/sis11framework\/contact","navigatorTitle":[{"text":"Contact","kind":"identifier"}],"title":"Contact","abstract":[],"type":"topic"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Sis11SDK":{"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Sis11SDK","abstract":[{"text":"Singleton instance for sis11sdk","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Sis11SDK"}],"navigatorTitle":[{"text":"Sis11SDK","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sis11framework\/sis11sdk","type":"topic","title":"Sis11SDK"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/StateCatalog":{"navigatorTitle":[{"text":"StateCatalog","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StateCatalog","kind":"identifier"}],"url":"\/documentation\/sis11framework\/statecatalog","abstract":[{"text":"State DTO","type":"text"}],"type":"topic","title":"StateCatalog","role":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/StateCatalog"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/QuotePortalProductResponse":{"role":"symbol","url":"\/documentation\/sis11framework\/quoteportalproductresponse","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"QuotePortalProductResponse"}],"type":"topic","title":"QuotePortalProductResponse","kind":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/QuotePortalProductResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuotePortalProductResponse"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/StepConfig":{"title":"StepConfig","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StepConfig","kind":"identifier"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/StepConfig","abstract":[{"type":"text","text":"Steps configuration controls"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"StepConfig","kind":"identifier"}],"url":"\/documentation\/sis11framework\/stepconfig","kind":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/IssueReason":{"kind":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueReason","url":"\/documentation\/sis11framework\/issuereason","navigatorTitle":[{"kind":"identifier","text":"IssueReason"}],"title":"IssueReason","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IssueReason"}],"type":"topic"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Issue":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Issue","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Issue","navigatorTitle":[{"kind":"identifier","text":"Issue"}],"title":"Issue","abstract":[],"url":"\/documentation\/sis11framework\/issue","role":"symbol","kind":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/IssueResponse":{"navigatorTitle":[{"kind":"identifier","text":"IssueResponse"}],"title":"IssueResponse","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueResponse","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IssueResponse"}],"url":"\/documentation\/sis11framework\/issueresponse","role":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/APIError":{"kind":"symbol","title":"APIError","type":"topic","role":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/APIError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"APIError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"APIError"}],"url":"\/documentation\/sis11framework\/apierror","abstract":[]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/EventReason":{"kind":"symbol","url":"\/documentation\/sis11framework\/eventreason","navigatorTitle":[{"kind":"identifier","text":"EventReason"}],"title":"EventReason","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/EventReason","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EventReason"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/SelfServiceConfiguration":{"kind":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/SelfServiceConfiguration","url":"\/documentation\/sis11framework\/selfserviceconfiguration","navigatorTitle":[{"kind":"identifier","text":"SelfServiceConfiguration"}],"title":"SelfServiceConfiguration","abstract":[{"text":"Self Service Response Config DTO","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelfServiceConfiguration"}],"type":"topic"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/City":{"kind":"symbol","title":"City","navigatorTitle":[{"text":"City","kind":"identifier"}],"abstract":[{"text":"City DTO","type":"text"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/City","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"City"}],"url":"\/documentation\/sis11framework\/city","type":"topic"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/RepoClaimDTO":{"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/RepoClaimDTO","type":"topic","url":"\/documentation\/sis11framework\/repoclaimdto","title":"RepoClaimDTO","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RepoClaimDTO","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"RepoClaimDTO","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Priority":{"title":"Priority","role":"symbol","url":"\/documentation\/sis11framework\/priority","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Priority","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Priority"}],"navigatorTitle":[{"text":"Priority","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Coverage":{"abstract":[],"navigatorTitle":[{"text":"Coverage","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coverage","kind":"identifier"}],"title":"Coverage","url":"\/documentation\/sis11framework\/coverage","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Coverage","type":"topic"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/PortalData":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PortalData"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/PortalData","kind":"symbol","abstract":[{"text":"Portal Data DTO","type":"text"}],"url":"\/documentation\/sis11framework\/portaldata","type":"topic","title":"PortalData","role":"symbol","navigatorTitle":[{"text":"PortalData","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/MobilePayment":{"abstract":[{"type":"text","text":"Mobile Payment DTO"}],"role":"symbol","kind":"symbol","url":"\/documentation\/sis11framework\/mobilepayment","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MobilePayment"}],"type":"topic","title":"MobilePayment","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/MobilePayment","navigatorTitle":[{"text":"MobilePayment","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/PayPlan":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PayPlan"}],"type":"topic","navigatorTitle":[{"text":"PayPlan","kind":"identifier"}],"role":"symbol","url":"\/documentation\/sis11framework\/payplan","title":"PayPlan","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/PayPlan","kind":"symbol","abstract":[]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Repository":{"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Repository","type":"topic","url":"\/documentation\/sis11framework\/repository","title":"Repository","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Repository","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Common repository options","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"- Authors:"},{"text":" ","type":"text"},{"type":"text","text":"Noel Obando"},{"type":"text","text":" "},{"text":"- Copyright: Axxis-Systems","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Repository"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/ReturnedUser":{"title":"ReturnedUser","navigatorTitle":[{"text":"ReturnedUser","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReturnedUser"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ReturnedUser","abstract":[],"url":"\/documentation\/sis11framework\/returneduser","kind":"symbol","role":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Sis11FrameworkVersionNumber":{"title":"Sis11FrameworkVersionNumber","kind":"symbol","url":"\/documentation\/sis11framework\/sis11frameworkversionnumber","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Sis11FrameworkVersionNumber","role":"symbol","abstract":[{"type":"text","text":"Project version number for Sis11Framework."}],"type":"topic","fragments":[{"text":"Sis11FrameworkVersionNumber","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Catalog":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Catalog","kind":"identifier"}],"navigatorTitle":[{"text":"Catalog","kind":"identifier"}],"title":"Catalog","type":"topic","abstract":[{"type":"text","text":"Catalog names"}],"url":"\/documentation\/sis11framework\/catalog","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Catalog"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/RepoClaim":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RepoClaim"}],"abstract":[{"type":"text","text":"Claim Repository"}],"title":"RepoClaim","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RepoClaim"}],"url":"\/documentation\/sis11framework\/repoclaim","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/RepoClaim"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/RepoLifePolicyDTO":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RepoLifePolicyDTO","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RepoLifePolicyDTO"}],"url":"\/documentation\/sis11framework\/repolifepolicydto","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/RepoLifePolicyDTO","title":"RepoLifePolicyDTO","role":"symbol","abstract":[]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Relationship":{"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Relationship","url":"\/documentation\/sis11framework\/relationship","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Relationship","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Relationship","kind":"identifier"}],"title":"Relationship","abstract":[{"type":"text","text":"Contact Relationship DTO"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Currency":{"abstract":[{"text":"Currency DTO","type":"text"}],"url":"\/documentation\/sis11framework\/currency","type":"topic","title":"Currency","role":"symbol","navigatorTitle":[{"text":"Currency","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Currency","kind":"identifier"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Currency","kind":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/SelfService":{"navigatorTitle":[{"kind":"identifier","text":"SelfService"}],"title":"SelfService","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/SelfService","type":"topic","abstract":[{"type":"text","text":"Self Service DTO"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelfService"}],"url":"\/documentation\/sis11framework\/selfservice","kind":"symbol","role":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/DoCmd-swift.class":{"type":"topic","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/DoCmd-swift.class","url":"\/documentation\/sis11framework\/docmd-swift.class","abstract":[{"text":"DoCmd Action","type":"text"}],"title":"DoCmd","navigatorTitle":[{"kind":"identifier","text":"DoCmd"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DoCmd"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Product":{"kind":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Product","url":"\/documentation\/sis11framework\/product","navigatorTitle":[{"kind":"identifier","text":"Product"}],"title":"Product","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Product","kind":"identifier"}],"type":"topic"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/doCmdData":{"role":"symbol","navigatorTitle":[{"text":"doCmdData","kind":"identifier"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/doCmdData","kind":"symbol","url":"\/documentation\/sis11framework\/docmddata","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"doCmdData"}],"type":"topic","title":"doCmdData","abstract":[{"type":"text","text":"Generic data to doCmd parameters"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Sis11FrameworkVersionString":{"fragments":[{"kind":"identifier","text":"Sis11FrameworkVersionString"}],"abstract":[{"type":"text","text":"Project version string for Sis11Framework."}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Sis11FrameworkVersionString","type":"topic","title":"Sis11FrameworkVersionString","role":"symbol","kind":"symbol","url":"\/documentation\/sis11framework\/sis11frameworkversionstring"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework":{"abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/sis11framework","type":"topic","title":"Sis11Framework","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/GetPingDTO":{"type":"topic","url":"\/documentation\/sis11framework\/getpingdto","title":"GetPingDTO","navigatorTitle":[{"kind":"identifier","text":"GetPingDTO"}],"kind":"symbol","abstract":[{"type":"text","text":"Get Ping DTO"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetPingDTO","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/GetPingDTO"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Options":{"title":"Options","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Options","type":"topic","role":"symbol","navigatorTitle":[{"text":"Options","kind":"identifier"}],"abstract":[{"type":"text","text":"Quotation options DTO"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Options","kind":"identifier"}],"url":"\/documentation\/sis11framework\/options","kind":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Country":{"title":"Country","type":"topic","url":"\/documentation\/sis11framework\/country","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Country","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Country"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Country DTO","type":"text"}],"navigatorTitle":[{"text":"Country","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Premium":{"url":"\/documentation\/sis11framework\/premium","title":"Premium","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Premium","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Premium","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Premium","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/LifePolicy":{"abstract":[],"title":"LifePolicy","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/LifePolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LifePolicy","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/sis11framework\/lifepolicy","navigatorTitle":[{"kind":"identifier","text":"LifePolicy"}],"type":"topic"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/InsuredEvent":{"navigatorTitle":[{"kind":"identifier","text":"InsuredEvent"}],"title":"InsuredEvent","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"InsuredEvent","kind":"identifier"}],"url":"\/documentation\/sis11framework\/insuredevent","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/InsuredEvent"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/RepoLifePolicy":{"kind":"symbol","abstract":[{"type":"text","text":"Policy Repository"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RepoLifePolicy"}],"url":"\/documentation\/sis11framework\/repolifepolicy","role":"symbol","title":"RepoLifePolicy","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/RepoLifePolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RepoLifePolicy","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Credentials":{"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Credentials","title":"Credentials","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"Credentials","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Credentials"}],"type":"topic","role":"symbol","url":"\/documentation\/sis11framework\/credentials"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/SDK":{"url":"\/documentation\/sis11framework\/sdk","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"SDK","kind":"identifier"},{"kind":"text","text":": "},{"text":"Sis11SDK","kind":"typeIdentifier","preciseIdentifier":"s:14Sis11Framework0A3SDKC"}],"title":"SDK","abstract":[],"type":"topic","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/SDK","kind":"symbol","role":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/InsuredObject":{"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/InsuredObject","url":"\/documentation\/sis11framework\/insuredobject","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InsuredObject","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InsuredObject"}],"title":"InsuredObject","abstract":[]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/ReturnedUserOutData":{"title":"ReturnedUserOutData","url":"\/documentation\/sis11framework\/returneduseroutdata","navigatorTitle":[{"kind":"identifier","text":"ReturnedUserOutData"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ReturnedUserOutData","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReturnedUserOutData","kind":"identifier"}]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Claim":{"title":"Claim","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Claim"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Claim","kind":"identifier"}],"url":"\/documentation\/sis11framework\/claim","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Claim","abstract":[]},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/AuthErrors":{"abstract":[],"title":"AuthErrors","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthErrors"}],"url":"\/documentation\/sis11framework\/autherrors","navigatorTitle":[{"kind":"identifier","text":"AuthErrors"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/AuthErrors"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Insured":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Insured","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Insured","navigatorTitle":[{"text":"Insured","kind":"identifier"}],"title":"Insured","abstract":[],"url":"\/documentation\/sis11framework\/insured","role":"symbol","kind":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/ContactDataOutData":{"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/ContactDataOutData","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactDataOutData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ContactDataOutData"}],"role":"symbol","title":"ContactDataOutData","abstract":[],"url":"\/documentation\/sis11framework\/contactdataoutdata","type":"topic","kind":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/IssueType":{"navigatorTitle":[{"kind":"identifier","text":"IssueType"}],"type":"topic","url":"\/documentation\/sis11framework\/issuetype","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IssueType"}],"title":"IssueType","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueType"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/doCmd-swift.struct":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"doCmd","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/doCmd-swift.struct","navigatorTitle":[{"text":"doCmd","kind":"identifier"}],"title":"doCmd","abstract":[{"type":"text","text":"doCmd Dto"}],"url":"\/documentation\/sis11framework\/docmd-swift.struct","role":"symbol","kind":"symbol"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/IssueRequest":{"url":"\/documentation\/sis11framework\/issuerequest","role":"symbol","title":"IssueRequest","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IssueRequest"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IssueRequest"}],"abstract":[],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/IssueRequest"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/QuoteConfig":{"role":"symbol","url":"\/documentation\/sis11framework\/quoteconfig","title":"QuoteConfig","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QuoteConfig","kind":"identifier"}],"abstract":[{"text":"Self Service Quote configuration.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QuoteConfig"}],"identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/QuoteConfig"},"doc://com.axxis-systems.Sis11Framework/documentation/Sis11Framework/Portal":{"kind":"symbol","identifier":"doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Portal","url":"\/documentation\/sis11framework\/portal","navigatorTitle":[{"kind":"identifier","text":"Portal"}],"title":"Portal","abstract":[{"type":"text","text":"Portal Product operations."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Portal","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Variables","identifiers":["doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Sis11FrameworkVersionNumber","doc:\/\/com.axxis-systems.Sis11Framework\/documentation\/Sis11Framework\/Sis11FrameworkVersionString"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}